### ISSUE TITLE
Initialize Project

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a running React Native project ready with the component library added.
CI strategy is set and configured -> Compile errors with Github Actions.
Branching strategy is discussed.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by valentingc** [comment]
@DominicLuidold: Pipelines
@valentingc : Project init

**Comment by DominicLuidold** [comment]
> @DominicLuidold: Pipelines
> @valentingc : Project init

I'll have a look at the CI infrastructure and the GitHub Actions pipelines to automate the most common steps when creating PRs:
* Compile errors
* Styling

**Comment by DominicLuidold** [comment]
The following things are nice to have, but don't need to be implemented immediately:
* ESLint
* Prettier

**Comment by valentingc** [comment]
@DominicLuidold will implement as soon as login is merged to dev

**Comment by valentingc** [comment]
@DominicLuidold  this is done now, isn't it?

**Comment by DominicLuidold** [comment]
@valentingc AFAIK, we still need to implement Eslint and add it to the CI..
