### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#12]
**Describe the solution you'd like**
Implement the technical basis for language switching.

**Additional context**
None.

**Comment by whiteclouds7** [comment]
[medium article on how to use i18n](https://itnext.io/how-to-use-i18next-in-react-native-expo-476fa80bd92c)
[react-i18next](https://react.i18next.com/)
[expo-localization](https://docs.expo.io/versions/latest/sdk/localization/)
