### ISSUE TITLE
Implement proper screen header

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#19]
**Describe the solution you'd like**
Implement a proper screen header that uses React Native Navigation.
List of features include:

- Title (center)
- Avatar (right)
  - clickable, callback can be provided
  - Component must be provided
- Action Button
  - Component must be provided
  - Can for example be a share button, or "Save" button with an icon
- Back button must stay working as is from react navigation

**Additional context**
-

**Comment by valentingc** [comment]
I added a first draft that might be useful: 4a4791fd3833e290e7872b6936d19bc02308611d

**Comment by DominicLuidold** [comment]
> Fix a css workaround:

This has been already been fixed in 81d38feb26ac876e136198b6d109235e486599a6. Depending on which branch gets merged first, we'll likely have a small conflict. Should be easy to fix though.

**Comment by DominicLuidold** [comment]
@valentingc I've rebased the branch based on the last few PRs that were merged into `develop`.
