### ISSUE TITLE
Implement Login screen

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Login uses the backend to check the user's credentials (username, password) and forwards the user to another screen. The current user information is stored so that other components can access the user information.

**Describe alternatives you've considered**
None

**Additional context**
Login works with JWT access and refresh tokens. Need to be securely stored (SecureStorage).
Try to use Storybook for this component.

![IMG_0346](https://user-images.githubusercontent.com/65771894/114028703-0d81b080-9879-11eb-9075-db8896a336b1.JPG)

**Comment by alexw-at** [comment]
This is not done, communication with the backend is still missing

**Comment by DominicLuidold** [comment]
> This is not done, communication with the backend is still missing

Sorry! Closing the issue was just too tempting to not do it.. (and I quite apparently forgot about that, even though I commented on your PR during the review.. 😅).
