### ISSUE TITLE
Implement Like and Dislike

### ISSUE THREAD

**Issue by whiteclouds7** [vacatius/mobile-app#23]
**Describe the solution you'd like**
Add like and dislike amount to each activity in GraphQL and database in order to add and show it like described in #4 

**Additional context**
We will also have to persist the users which liked/disliked an activity in order to prevent them from liking/disliking an activity several times as well as liking and disliking the same activity

**Comment by valentingc** [comment]
@whiteclouds7 : This is now Implemented. 

Mutations/Queries created:
```
mutation createActivityReaction($input: CreateActivityReactionInput!) {
  createActivityReaction(data: $input) {
    id
    activity {
      id
    }
    addedByUser {
      username
    }
    activityReactionType
  }
}

mutation updateActivityReaction($input: UpdateActivityReactionInput!) {
  updateActivityReaction(data: $input) {
    id
    activity {
      id
    }
    addedByUser {
      username
    }
    activityReactionType
  }
}


query getActivityReactions($activityId: String!) {
  activityReactions(
    activityId: $activityId
  ) {
    id
    activityReactionType
    activity {
      id
    }
  }
}
```


You can also select them in any other query where you select an Activity, for example, like this:
```
query trips {
  trips {
    itinerary {
      name
      activities {
        name
        activityReactions {
          id
          addedByUser {
            username
          }
          activityReactionType
        }
      }
    }
  }
```
Please adapt the field selection according to your needs, you can explore all fields in the GraphQL Playground.
