### ISSUE TITLE
Dashboard avatar color should be unique

### ISSUE THREAD

**Issue by whiteclouds7** [vacatius/mobile-app#29]
**Describe the bug**

**To Reproduce**
1. Go to 'Dashboard'
4. Error:
 - User Avatar has different colors, but is the same person

**Expected behavior**
user avatar should have the same color accross all trips but also for the profile avatar (right top)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65771894/115396819-b5866a80-a1e5-11eb-8999-2eec3bbd6e16.png)

**Additional context**

**Comment by valentingc** [comment]
Maybe use something like https://www.npmjs.com/package/string-to-color or https://www.npmjs.com/package/color-hash ?
