### ISSUE TITLE
Implement View and Edit Trip Details screen

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#5]
**Describe the solution you'd like**
- Navbar button click redirects to trip Details 
- offers possibility to read OR edit name, description, trip members

**Describe alternatives you've considered**

![IMG_0364](https://user-images.githubusercontent.com/65771894/117012125-e63ec780-acee-11eb-9d04-494745eb5331.JPG)
![IMG_0368](https://user-images.githubusercontent.com/65771894/117012169-f48ce380-acee-11eb-8e3c-f3d29656327f.JPG)
![IMG_0373](https://user-images.githubusercontent.com/65771894/117012177-f787d400-acee-11eb-83dd-b468d218503c.jpg)

**Comment by valentingc** [comment]
Two new mutations for leaving a trip (leaveTrip) and removing a trip member as an admin (removeMemberFromTrip) are now implemented in the backend.

**Comment by DominicLuidold** [comment]
@vacatius/mobile-app-team I think we need to talk about who is able to remove members from a trip, whether someone can leave a trip (and what's happening when the creator of the trip decides to do so!) and if we want to offer an option to delete a trip.

**Comment by DominicLuidold** [comment]
Results from the discussion:
* Deleting a trip is currently **not** possible (might get implemented in a future update)
* An _admin_ (creator of the trip) can remove any members, **excluding** themselve
* An _admin_ cannot leave the trip
* A trip member can leave the group by pressing an addtional button below the member list
