### ISSUE TITLE
Can't press stuff when keyboard is open

### ISSUE THREAD

**Issue by alexw-at** [vacatius/mobile-app#59]
**Describe the bug**
Can't press stuff when keyboard is open

**To Reproduce**
1. Go to login
2. Click on username input
3. Can't press login button while keyboard is open

**Expected behavior**
Can press button while keyboard is open

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11

**Comment by DominicLuidold** [comment]
I'll have a look at this tomorrow and see if this is bug also occurs on iOS or if it's OS specific. Until then, I've assigned the `Android` label.

**Comment by valentingc** [comment]
@vacatius/mobile-app-team I think the same happens on iOS. This comes from the smooth scrolling library that we use (react-native-keyboard-aware-scroll-view). Maybe we should give the recommended approach from expo example another try, but it didn't work for me back then. But maybe you get the hang of it @DominicLuidold ? 😃

**Comment by alexw-at** [comment]
When using `<KeyboardAwareScrollView keyboardShouldPersistTaps="handled">` it works as expected
