### ISSUE TITLE
Implement Add Trip screen

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#6]
**Describe the solution you'd like**
Pressing the floating action button "plan trip" on the Dashboard screen redirects to a new screen to create a trip.

Screen offers
- Input fields for name and description
- Button to create the trip
- Cancel button to return to the Dashboard screen

**Additional context**
![IMG_0348](https://user-images.githubusercontent.com/26229513/114031954-263f9580-987c-11eb-926b-f4dd294d51c6.JPG)

**Comment by DominicLuidold** [comment]
@valentingc This issue should be ready to get closed, right?
