### ISSUE TITLE
Implement View and Edit Activity screen

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#8]
**Describe the solution you'd like**
Pressing the "Add Activity" / "Edit Activity" buttons at the Trip Itinerary screen (in an activity group) redirects to a new screen to view or edit an activity.

Currently, documents are not implemented for activities.

**Additional context**
None.

![IMG_0352](https://user-images.githubusercontent.com/26229513/114032308-7cacd400-987c-11eb-924b-45cea5d51de6.JPG)
![IMG_0351](https://user-images.githubusercontent.com/26229513/114032346-82a2b500-987c-11eb-9276-71c042f21c63.JPG)

**Comment by whiteclouds7** [comment]
Some input on how to create a datepicker component with formik
https://codesandbox.io/s/formik-react-datepicker-demo-he69x?file=/DatePicker.jsx:177-257
https://github.com/henninghall/react-native-date-picker
https://formik.org/docs/api/useField
