### ISSUE TITLE
Implement Share Trip screen

### ISSUE THREAD

**Issue by valentingc** [vacatius/mobile-app#9]
**Describe the solution you'd like**
After adding a trip or when pressing the share button of a trip, a new screen opens up that offers the possibility to share this trip with friends by retrieving a link.

**Additional context**
None.

![IMG_0349](https://user-images.githubusercontent.com/26229513/114032564-b8479e00-987c-11eb-8c8d-4320476160b3.JPG)

**Comment by valentingc** [comment]
@DominicLuidold  You can use this mutation to create an invitation that can be shared:

```
mutation createInvitation($input: CreateInvitationInput!) {
	createInvitation(data: $input) {
		id
		status
		createdByUser {
			displayName
		}
		acceptedUsersCount
		tripId
	}
}
```
This creates the invitation itself. A sharable link has to be created by the App itself, e.g. by using something like [this](https://docs.expo.io/guides/linking/#in-the-expo-go-app).

**Comment by DominicLuidold** [comment]
> This creates the invitation itself. A sharable link has to be created by the App itself, e.g. by using something like [this](https://docs.expo.io/guides/linking/#in-the-expo-go-app).

@valentingc I think we need to discuss with the team how we want to deal with shareable links. I have had a look at the documentation and I don't think I can make this decision on my own.

**Comment by DominicLuidold** [comment]
As we've discussed earlier in our team meeting, we _won't_ use [iOS universal links](https://docs.expo.io/guides/linking/#universal-links-on-ios) nor [Android deep links](https://docs.expo.io/guides/linking/#deep-links-on-android). We rather use a custom link (`https://vacatius.com/invite/<invitation-id>`) which will make us of the custom app scheme `vacatius://` introduced in c0dbad646807771b580dfbc364a6c68a18d4c157.
